### ISSUE TITLE
2.8 -> 3.2 mocking does not work on short-form abc.map(makeFoo)

### ISSUE THREAD

**Issue by mcbain** [timkindberg/jest-when#65]
```javascript
import {makeFoo} from "foo"
import {when} from "jest-when"
when(makeFoo)
    .calledWith('bar')
    .mockReturnValue(123)

abc.map(makeFoo)              // mocking does not work
abc.map(x => makeFoo(x)) //  mocking works
```

Any idea why the short form mocking does not work with 3.2 ?

**Comment by mcbain** [comment]
No, but no time to really dig into it. We end up using the longer form which is even more readable :)

**Comment by timkindberg** [comment]
Figured it out... it's because calledWith needs to be explicit since v3, you must define all args passed to the function. Partial definitions of args are no longer supported. And when you map the function gets passed `value, index, array`, not just the `value`. So it wasn't a match.

You would have to change your code a bit:
```
when(makeFoo)
    .calledWith('bar', expect.anything(), expect.anything())
    .mockReturnValue(123)
```
