### ISSUE TITLE
ES6 Class Support?

### ISSUE THREAD

**Issue by ycmjason** [timkindberg/jest-when#9]
Thanks for creating this wonderful package! Absolutely loving it!

Any plan on supporting ES6 Class constructor? Something like the following?

```js
when(Car)
  .constructWith('Mercedes')
  .mockInstance({
    color: 'red',
    price: 50,
  });
```

Just an idea! 😄

**Comment by timkindberg** [comment]
Thank you for the kind words!

Hmm, I think the idea of this lib is to simply add a `.calledWith()` modifier to existing mock capabilities. Since core jest does not natively provide any specific helpers for ES6 classes (see https://jestjs.io/docs/en/es6-class-mocks) then I'm inclined to not add them. You can instead follow the advice on their website.

However, we should add support for `mockImplementation`, which [I've already suggested](https://github.com/timkindberg/jest-when/issues/7#issuecomment-436719507).
